CREATE TABLE message_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    contact_id uuid,
    phone_number text NOT NULL,
    message_content text NOT NULL,
    media_url text,
    message_type text DEFAULT 'text' CHECK (message_type IN ('text',
    'image',
    'document',
    'video',
    'audio')),
    status text DEFAULT 'pending' CHECK (status IN ('pending',
    'sent',
    'delivered',
    'failed',
    'read')),
    platform text DEFAULT 'web' CHECK (platform IN ('web',
    'api')),
    sent_at timestamptz,
    delivered_at timestamptz,
    read_at timestamptz,
    error_message text,
    created_at timestamptz DEFAULT now()
);