[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_ARGS = "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage"